apiVersion: apps/v1
kind: Deployment
metadata:
  creationTimestamp: null
  name: partner-catalog-staging
spec:
  selector: {}
  strategy: {}
  template:
    metadata:
      creationTimestamp: null
    spec:
      containers:
      - image: quay.io/redhat-user-workloads-stage/mreid1-tenant/partner-catalog-staging/partner-catalog-staging@sha256:6d8a1a8c267ad0019273fcfdd18caf3dd5b50f341a4d80bafa03a21f6f197ca7
        name: my-java-springboot
        resources: {}
status: {}
